USE [master]
GO

/****** Object:  Database [BaseDiploma]    Script Date: 5/8/2026 17:21:49 ******/
CREATE DATABASE [BaseDiploma]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BaseDiploma', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\BaseDiploma.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BaseDiploma_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\BaseDiploma_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BaseDiploma].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BaseDiploma] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BaseDiploma] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BaseDiploma] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BaseDiploma] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BaseDiploma] SET ARITHABORT OFF 
GO

ALTER DATABASE [BaseDiploma] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BaseDiploma] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BaseDiploma] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BaseDiploma] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BaseDiploma] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BaseDiploma] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BaseDiploma] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BaseDiploma] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BaseDiploma] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BaseDiploma] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BaseDiploma] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BaseDiploma] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BaseDiploma] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BaseDiploma] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BaseDiploma] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BaseDiploma] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BaseDiploma] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BaseDiploma] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BaseDiploma] SET  MULTI_USER 
GO

ALTER DATABASE [BaseDiploma] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BaseDiploma] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BaseDiploma] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BaseDiploma] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BaseDiploma] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BaseDiploma] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [BaseDiploma] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BaseDiploma] SET  READ_WRITE 
GO


